### PR TITLE
add filtering capabilities to the results table

### PR DESCRIPTION
**Pull request by eranra**
Adding filtering capabilities to the table view::

image

### CODE REVIEW

**Comment by eranra** [comment]
In addition, for more clarity moving the config.py file under the folder "utils"

**Review by rachelt44 — CHANGES_REQUESTED** [review]
@eranra currently all features in the filters are treated as categorical. This is not natural for numeric features and also might cause a lot of "manual" filtering. Can you instead do the following:
- keep filtering for all categorical features as they are today
- For numeric input features, display a range of integer values 
- For numeric output features, display a range of float values
The definition of numeric/categorical input and output features is already known to the UI from the data metadata file that the core generates

**Comment by eranra** [comment]
@rachelt44 look on the slide I shared above --- ^^^ it is showing you numeric filtering ^^^

**Comment by eranra** [comment]
> > @rachelt44 look on the slide I shared above --- ^^^ it is showing you numeric filtering ^^^
> > (( The code automatically detects for all the clomns in the table if they are numeric or categorial and creates relevant filters for the data basedon that., ))
> 
> When I ran the code locally, all features were detected as categorical, so it didn't work for me. Also, in the slide you showed, it shows real numbers for integer features, which doesn't make sense. We don't want a 21.97 filter for number of processors. Is there a way to fix it?

Code is updated @rachelt44 please check :-)

**Comment by eranra** [comment]
image

**Comment by rachelt44** [comment]
> > > @rachelt44 look on the slide I shared above --- ^^^ it is showing you numeric filtering ^^^
> > > (( The code automatically detects for all the clomns in the table if they are numeric or categorial and creates relevant filters for the data basedon that., ))
> > 
> > 
> > When I ran the code locally, all features were detected as categorical, so it didn't work for me. Also, in the slide you showed, it shows real numbers for integer features, which doesn't make sense. We don't want a 21.97 filter for number of processors. Is there a way to fix it?
> 
> Code is updated @rachelt44 please check :-)

@eranra works now!

**Review by rachelt44 — APPROVED** [review]

**Pull request merged**
